name: Deploy to Heroku

on:
  push:
    branches:
      - heroku # deploy only on pushes to heroku (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:token &> /dev/null
          heroku auth:token > ~/.netrc
          heroku whoami
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Push to Heroku
        run: |
          heroku git:remote --app "$HEROKU_APP_NAME"
          git push heroku HEAD:main --force
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
